version: '3'

networks:
  devmode:

services:
  orderer:
    networks:
      - devmode
    container_name: orderer
    image: hyperledger/fabric-orderer:$TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=orderer.block
      - ORDERER_GENERAL_LOCALMSPID=DEFAULT
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../../msp:/etc/hyperledger/msp
      - ../../crypto/orderer.block:/etc/hyperledger/fabric/orderer.block
    ports:
      - 7050:7050

  peer:
    networks:
      - devmode
    container_name: peer
    image: hyperledger/fabric-peer:$TAG
    environment:
      - CORE_PEER_ID=peer
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    volumes:
        - /var/run/:/host/var/run/
        - ../../msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer

#  cli:
#    networks:
#      - devmode
#    container_name: cli
#    image: hyperledger/fabric-tools:$TAG
#    tty: true
#    environment:
#      - GOPATH=/opt/gopath
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      - CORE_LOGGING_LEVEL=DEBUG
#      - CORE_PEER_ID=cli
#      - CORE_PEER_ADDRESS=peer:7051
#      - CORE_PEER_LOCALMSPID=DEFAULT
#      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
#    working_dir: /var/chaincodedev
#    command: /bin/bash -c './script.sh'
#    volumes:
#        - /var/run/:/host/var/run/
#        - ../../msp:/etc/hyperledger/msp
#        - ../../bin:/var/chaincode
#    depends_on:
#      - orderer
#      - peer